from enum import Enum


class SubmissionStatus(str, Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class JourneyStep(str, Enum):
    NOT_STARTED = "NOT_STARTED"
    ONBOARDING_SUBMITTED = "ONBOARDING_SUBMITTED"
    QUIZ_SUBMITTED_PENDING = "QUIZ_SUBMITTED_PENDING"
    INTRO_UNLOCKED = "INTRO_UNLOCKED"
    SCENARIO_SUBMITTED_PENDING = "SCENARIO_SUBMITTED_PENDING"
    ADVANCED_UNLOCKED = "ADVANCED_UNLOCKED"
