"""add crm proposals

Revision ID: 46c48b70ef00
Revises: 350b786ec702
Create Date: 2026-03-11 03:29:18.351923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46c48b70ef00'
down_revision: Union[str, Sequence[str], None] = '350b786ec702'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crm_proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('instructor_user_id', sa.Integer(), nullable=False),
    sa.Column('proposal_url', sa.String(length=500), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instructor_user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_id'], ['crm_leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_proposals_id'), 'crm_proposals', ['id'], unique=False)
    op.create_index(op.f('ix_crm_proposals_instructor_user_id'), 'crm_proposals', ['instructor_user_id'], unique=False)
    op.create_index(op.f('ix_crm_proposals_lead_id'), 'crm_proposals', ['lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crm_proposals_lead_id'), table_name='crm_proposals')
    op.drop_index(op.f('ix_crm_proposals_instructor_user_id'), table_name='crm_proposals')
    op.drop_index(op.f('ix_crm_proposals_id'), table_name='crm_proposals')
    op.drop_table('crm_proposals')
    # ### end Alembic commands ###
