"""add onsite logs

Revision ID: 8552210a9253
Revises: 80efed28a4ea
Create Date: 2026-03-10 22:46:35.495571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8552210a9253'
down_revision: Union[str, Sequence[str], None] = '80efed28a4ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onsite_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_type', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('evidence_url', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'VERIFIED', 'REJECTED', name='onsite_log_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onsite_logs_id'), 'onsite_logs', ['id'], unique=False)
    op.create_index(op.f('ix_onsite_logs_user_id'), 'onsite_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_onsite_logs_user_id'), table_name='onsite_logs')
    op.drop_index(op.f('ix_onsite_logs_id'), table_name='onsite_logs')
    op.drop_table('onsite_logs')
    # ### end Alembic commands ###
