"""points ledger unique per entity reason

Revision ID: 896ccd5d3ea7
Revises: 999c4285367e
Create Date: 2026-03-02 03:03:35.763612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '896ccd5d3ea7'
down_revision: Union[str, Sequence[str], None] = '999c4285367e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_points_once_per_entity_reason', 'points_ledger', ['entity_type', 'entity_id', 'reason'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_points_once_per_entity_reason', 'points_ledger', type_='unique')
    # ### end Alembic commands ###
