"""week4 add content items and access logs

Revision ID: 9fccd3f102a8
Revises: 4a200d67d38b
Create Date: 2026-02-18 10:29:46.002784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fccd3f102a8'
down_revision: Union[str, Sequence[str], None] = '4a200d67d38b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_items_id'), 'content_items', ['id'], unique=False)
    op.create_index(op.f('ix_content_items_key'), 'content_items', ['key'], unique=False)
    op.create_table('content_access_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content_key', sa.String(length=50), nullable=False),
    sa.Column('accessed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_access_logs_content_key'), 'content_access_logs', ['content_key'], unique=False)
    op.create_index(op.f('ix_content_access_logs_id'), 'content_access_logs', ['id'], unique=False)
    op.create_index(op.f('ix_content_access_logs_user_id'), 'content_access_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_access_logs_user_id'), table_name='content_access_logs')
    op.drop_index(op.f('ix_content_access_logs_id'), table_name='content_access_logs')
    op.drop_index(op.f('ix_content_access_logs_content_key'), table_name='content_access_logs')
    op.drop_table('content_access_logs')
    op.drop_index(op.f('ix_content_items_key'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_id'), table_name='content_items')
    op.drop_table('content_items')
    # ### end Alembic commands ###
